version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: usercopy-backend-dev
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=development
      - PORT=8090
      - FRONTEND_URL=http://localhost:8089
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: npm run dev
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: usercopy-frontend-dev
    ports:
      - "8089:8089"
    environment:
      - NODE_ENV=development
      - PORT=8089
      - NEXT_PUBLIC_API_URL=http://backend:8090/api
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next
    command: npm run dev
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_node_modules:
  frontend_node_modules:
  frontend_next:
